-- 1. Tabela de Serviços Parceiros (embutidos)
CREATE TABLE parceiros (
    id_parceiro   NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome_servico  VARCHAR2(50) NOT NULL,
    api_endpoint  VARCHAR2(255) NOT NULL
);

-- 2. Tabela de Planos do Hub (ex: Plano Premium que inclui outros parceiros)
CREATE TABLE planos (
    id_plan       NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome_plano    VARCHAR2(50) NOT NULL,
    preco         NUMBER(5,2) NOT NULL
);

-- 3. Relacionamento Muitos para Muitos: Quais parceiros estão em cada plano
CREATE TABLE plano_parceiros (
    id_plan       NUMBER REFERENCES planos(id_plan),
    id_parceiro   NUMBER REFERENCES parceiros(id_parceiro),
    PRIMARY KEY (id_plan, id_parceiro)
);

-- 4. Tabela de Clientes e suas Assinaturas Ativas
CREATE TABLE assinaturas_cliente (
    id_assinatura     NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome_cliente      VARCHAR2(100) NOT NULL,
    email_cliente     VARCHAR2(100) NOT NULL,
    id_plan           NUMBER REFERENCES planos(id_plan),
    status_assinatura VARCHAR2(20) DEFAULT 'PENDENTE', -- PENDENTE, ATIVO, ERRO
    data_criacao      DATE DEFAULT SYSDATE
);

-- Carga inicial de dados para o portfólio
INSERT INTO parceiros (nome_servico, api_endpoint) VALUES ('Crunchyroll Premium', 'https://api.mock.hubstreaming.com/v1/activate/crunchyroll');
INSERT INTO parceiros (nome_servico, api_endpoint) VALUES ('Paramount+ ', 'https://api.mock.hubstreaming.com/v1/activate/paramount');

INSERT INTO planos (nome_plano, preco) VALUES ('Hub Mecha & Action Pack', 49.90);

-- Vinculando os dois parceiros ao plano ID 1
INSERT INTO plano_parceiros (id_plan, id_parceiro) VALUES (1, 1);
INSERT INTO plano_parceiros (id_plan, id_parceiro) VALUES (1, 2);
COMMIT;